import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../app/providers.dart';
import '../../core/formatters/money.dart';
import '../../domain/models/models.dart';
import '../../data/ai/ai_gateway.dart';
import '../widgets/app_shell.dart';
import '../../data/billing/entitlement_service.dart';
import '../../data/billing/entitlement_service.dart';

class SmartInputScreen extends ConsumerStatefulWidget { const SmartInputScreen({super.key}); @override ConsumerState<SmartInputScreen> createState()=>_SmartState(); }
class _SmartState extends ConsumerState<SmartInputScreen>{
 final input=TextEditingController(); _Draft? draft; String? error; bool aiBusy=false; bool aiUsed=false;
 @override void initState(){super.initState();_ensureConfig();}
 Future<void> _ensureConfig() async {final s=ref.read(storageProvider);final u=await s.read(key:'finaro.ai.url')??'';final k=await s.read(key:'finaro.ai.key')??'';final m=await s.read(key:'finaro.ai.model')??'';if(u.isNotEmpty)ref.read(aiConfigProvider.notifier).state=AiGatewayConfig(baseUrl:u,apiKey:k,model:m);}
 @override void dispose(){input.dispose();super.dispose();}
 void parse(){ final text=input.text.trim(); setState((){error=null;draft=null;}); if(text.isEmpty)return; _setLocalDraft(text); }
 void _setLocalDraft(String text){ final amount=_amount(text); if(amount==null){setState(()=>error='مبلغ را نتوانستم با اطمینان تشخیص بدهم. مثلاً «۸۰ هزار تومان».');return;} final isIncome=RegExp(r'حقوق|درآمد|دریافت|گرفتم').hasMatch(text); final isLiability=RegExp(r'قسط|چک|بدهی|تعهد').hasMatch(text); final kind=isIncome?'income':isLiability?'liability':'expense'; setState(()=>draft=_Draft(kind:kind,title:_title(text,isIncome?'درآمد':isLiability?'تعهد':'هزینه'),amount:amount,frequency:text.contains('ماه')?'ماهانه':'همین ماه',category:isIncome?'':_category(text))); }
 Future<void> parseWithAi() async { final text=input.text.trim(); if(text.isEmpty)return; setState(()=>aiBusy=true); try { await EntitlementService(ref.read(storageProvider)).consumeAi(); final out=await ref.read(aiGatewayProvider).smartInput(text); final data=(out['data'] is Map)?Map<String,dynamic>.from(out['data'] as Map):<String,dynamic>{}; final amount=(data['amountRials'] as num?)?.toInt(); final intent=(out['intent']??'create_expense').toString(); if(amount==null){setState(()=>error=((out['questions'] is List && (out['questions'] as List).isNotEmpty)?(out['questions'] as List).first.toString():'AI برای مبلغ به اطلاعات بیشتری نیاز دارد.'));return;} final kind=intent.contains('income')?'income':intent.contains('liability')?'liability':'expense'; setState(()=>draft=_Draft(kind:kind,title:(data['title']??text).toString(),amount:amount,frequency:(data['frequency']??'همین ماه').toString(),category:(data['category']??'متفرقه').toString())); } catch(e){ _setLocalDraft(text); setState(()=>error='AI در دسترس نبود؛ پیش‌نمایش محلی استفاده شد. ${e is AiGatewayException?e.message:''}'); } finally { if(mounted)setState(()=>aiBusy=false); } }
 int? _amount(String s){final m=RegExp(r'([۰-۹0-9][۰-۹0-9,٬\. ]*)\s*(میلیون|هزار|هزار تومان|تومان)?').firstMatch(s);if(m==null)return null;final digits=m.group(1)!.replaceAll(RegExp(r'[,٬\s]'),'').replaceAllMapped(RegExp(r'[۰-۹]'),(x)=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(x.group(0)!).toString());final n=int.tryParse(digits);if(n==null)return null;final unit=m.group(2)??'تومان';final toman=unit.contains('میلیون')?n*1000000:unit.contains('هزار')?n*1000:n;return toman*10;}
 String _title(String s,String fallback){final clean=s.replaceAll(RegExp(r'امروز|فردا|دیروز|ماهانه|هر ماه|تومان|میلیون|هزار|درآمد|حقوق|گرفتم|دارم|می‌دهم|دادم'),' ').trim();return clean.isEmpty?fallback:(clean.length>32?clean.substring(0,32):clean);}
 String _category(String s){if(s.contains('تاکسی')||s.contains('مترو')||s.contains('اسنپ'))return 'حمل‌ونقل';if(s.contains('اجاره')||s.contains('خانه'))return 'مسکن';if(s.contains('غذا')||s.contains('رستوران'))return 'خوراک';return 'متفرقه';}
 Future<void> confirm()async{final d=draft;if(d==null)return;final id=DateTime.now().microsecondsSinceEpoch.toString();final date=DateTime.now().toIso8601String().substring(0,10);final repo=ref.read(repoProvider);if(d.kind=='income'){await repo.addIncome(Income(id:id,title:d.title,amountRials:d.amount,frequency:d.frequency,start:date,payDay:d.frequency=='ماهانه'?DateTime.now().day:null));}else if(d.kind=='expense'){await repo.addExpense(Expense(id:id,title:d.title,amountRials:d.amount,frequency:d.frequency,category:d.category,date:date,startDate:date,paymentDay:d.frequency=='ماهانه'?DateTime.now().day:null));}else{await repo.addLiability(Liability(id:id,title:d.title,type:'بدهی',totalRials:d.amount,paymentDate:date));}ref.invalidate(incomesProvider);ref.invalidate(expensesProvider);ref.invalidate(liabilitiesProvider);setState((){draft=null;input.clear();});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('پیش‌نمایش تأیید و مورد در فضای محلی ثبت شد.')));}
 @override Widget build(BuildContext context)=>AppShell(title:'ثبت هوشمند',index:1,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[FinaroCard(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('فقط بگو چه اتفاقی افتاده',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('AI فقط متن را به داده ساختاریافته تبدیل می‌کند؛ محاسبه مالی و ثبت نهایی با Finaro است.',style:TextStyle(color:Theme.of(context).colorScheme.onSurfaceVariant)),const SizedBox(height:16),TextField(controller:input,maxLines:4,decoration:const InputDecoration(hintText:'مثلاً: امروز ۸۰ هزار تومان تاکسی دادم')),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:['امروز ۸۰ هزار تومان تاکسی دادم','حقوقم ماهی ۴۰ میلیون تومان است','ماهی ۵ میلیون قسط دارم'].map((x)=>ActionChip(label:Text(x),onPressed:(){input.text=x;parse();})).toList()),const SizedBox(height:14),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:aiBusy?null:parse,icon:const Icon(Icons.rule),label:const Text('پیش‌نمایش محلی'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:aiBusy?null:parseWithAi,icon:aiBusy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.auto_awesome),label:const Text('تحلیل با AI')))]),const SizedBox(height:8),Text('در نسخه رایگان، ۳ استفاده آزمایشی AI در نظر گرفته شده است.',style:TextStyle(fontSize:11,color:Theme.of(context).colorScheme.onSurfaceVariant))])),if(error!=null)...[const SizedBox(height:14),StatusBanner(icon:Icons.info_outline,title:'نیاز به بررسی',message:error!,tone:Colors.orange)],if(draft!=null)...[const SizedBox(height:14),FinaroCard(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SectionHeader(title:'پیش‌نمایش ثبت',subtitle:'این مرحله هنوز ثبت نهایی نیست.'),ListTile(contentPadding:EdgeInsets.zero,title:Text('',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(''),trailing:Text('')),ListTile(contentPadding:EdgeInsets.zero,title:Text(''),subtitle:Text(''),trailing:Text('')),Text(draft!.title,style:const TextStyle(fontWeight:FontWeight.w800)),Text(draft!.kind=='income'?'درآمد':draft!.kind=='expense'?'هزینه • ${draft!.category}':'تعهد • بدهی'),Align(alignment:Alignment.centerLeft,child:Text(MoneyFormatter.toman(draft!.amount),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))),const Divider(),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>setState(()=>draft=null),child:const Text('اصلاح'))),const SizedBox(width:10),Expanded(child:FilledButton.icon(onPressed:confirm,icon:const Icon(Icons.check),label:const Text('تأیید و ثبت')))])]))]]));
}
class _Draft{const _Draft({required this.kind,required this.title,required this.amount,required this.frequency,required this.category});final String kind,title,frequency,category;final int amount;}
