import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';
import 'package:flutter_riverpod/legacy.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../data/local/local_database.dart';
import '../data/repositories/financial_repository.dart';
import '../data/repositories/session_repository.dart';
import '../data/ai/ai_gateway.dart';
import '../data/billing/entitlement_service.dart';
final storageProvider=Provider((_)=>const FlutterSecureStorage());
final dbProvider=Provider((_)=>LocalDatabase.instance);
final repoProvider=Provider((r)=>FinancialRepository(r.watch(dbProvider)));
final sessionProvider=Provider((r)=>SessionRepository(r.watch(storageProvider)));
final profileProvider=FutureProvider((r)=>r.watch(repoProvider).profile());
final incomesProvider=FutureProvider((r)=>r.watch(repoProvider).incomes());
final expensesProvider=FutureProvider((r)=>r.watch(repoProvider).expenses());
final liabilitiesProvider=FutureProvider((r)=>r.watch(repoProvider).liabilities());
final categoriesProvider=FutureProvider((r)=>r.watch(repoProvider).categories());
final aiConfigProvider=StateProvider<AiGatewayConfig>((_)=>const AiGatewayConfig(baseUrl: ''));
final aiGatewayProvider=Provider((r)=>AiGateway(r.watch(aiConfigProvider)));
final entitlementProvider=FutureProvider((r)=>EntitlementService(r.watch(storageProvider)).current());
